"""Centralized logging configuration for the LEMO backend.

Goals
-----
1. One place that configures the root logger so every module that calls
   `logging.getLogger(__name__)` gets the same handlers and format.
2. Emit per-request logs that are easy to grep: every log line includes a
   short `req` id generated by `request_id_middleware`, so you can trace
   one user query across all three agents.
3. Persist everything to `lemo-fastapi/logs/server.log` with rotation, in
   addition to stdout, so you can tail it without scrolling the terminal.

Usage
-----
    from core.logging_config import setup_logging, request_id_middleware

    setup_logging()
    app.middleware("http")(request_id_middleware)
"""

from __future__ import annotations

import contextvars
import logging
import os
import time
import uuid
from logging.handlers import RotatingFileHandler
from pathlib import Path
from typing import Callable

# -----------------------------------------------------------------------------
# Request-id context: each HTTP request gets a short id ("r-a1b2c3") that is
# attached automatically to every log record via _RequestIdFilter. Agents don't
# need to pass it around — any logger.info(...) during that request picks it up.
# -----------------------------------------------------------------------------
_request_id_ctx: contextvars.ContextVar[str] = contextvars.ContextVar(
    "lemo_request_id", default="-"
)


def get_request_id() -> str:
    """Return the current request id (or '-' if outside a request)."""
    return _request_id_ctx.get()


def set_request_id(value: str) -> contextvars.Token:
    """Bind a request id to the current context and return the reset token."""
    return _request_id_ctx.set(value)


class _RequestIdFilter(logging.Filter):
    """Inject the current request id into every LogRecord."""

    def filter(self, record: logging.LogRecord) -> bool:
        record.request_id = get_request_id()
        return True


# -----------------------------------------------------------------------------
# Formatter
# -----------------------------------------------------------------------------

_CONSOLE_FORMAT = (
    "%(asctime)s | %(levelname)-5s | %(request_id)-10s | %(name)-28s | %(message)s"
)
_FILE_FORMAT = (
    "%(asctime)s | %(levelname)-5s | %(request_id)-10s | %(name)s | %(message)s"
)
_DATE_FORMAT = "%H:%M:%S"


def _make_console_handler(level: int) -> logging.Handler:
    handler = logging.StreamHandler()
    handler.setLevel(level)
    handler.setFormatter(logging.Formatter(_CONSOLE_FORMAT, datefmt=_DATE_FORMAT))
    handler.addFilter(_RequestIdFilter())
    return handler


def _make_file_handler(log_path: Path, level: int) -> logging.Handler:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    handler = RotatingFileHandler(
        log_path,
        maxBytes=5 * 1024 * 1024,  # 5 MB
        backupCount=5,
        encoding="utf-8",
    )
    handler.setLevel(level)
    handler.setFormatter(logging.Formatter(_FILE_FORMAT, datefmt="%Y-%m-%d %H:%M:%S"))
    handler.addFilter(_RequestIdFilter())
    return handler


# -----------------------------------------------------------------------------
# Public setup
# -----------------------------------------------------------------------------

_CONFIGURED = False


def setup_logging(
    *,
    level: str | int | None = None,
    log_dir: str | Path | None = None,
) -> None:
    """Configure the root logger exactly once per process.

    Parameters
    ----------
    level:
        Log level for the application loggers (defaults to LOG_LEVEL env or INFO).
    log_dir:
        Directory for the rotating `server.log` file (defaults to ./logs).
    """
    global _CONFIGURED
    if _CONFIGURED:
        return

    resolved_level = level or os.getenv("LOG_LEVEL", "INFO")
    if isinstance(resolved_level, str):
        resolved_level = logging.getLevelName(resolved_level.upper())
    if not isinstance(resolved_level, int):
        resolved_level = logging.INFO

    root = logging.getLogger()
    # Remove any handlers pre-installed by imports (basicConfig in a controller etc.)
    for existing in list(root.handlers):
        root.removeHandler(existing)

    root.setLevel(resolved_level)
    root.addHandler(_make_console_handler(resolved_level))

    log_dir_path = Path(log_dir) if log_dir else Path(__file__).resolve().parent.parent / "logs"
    try:
        root.addHandler(_make_file_handler(log_dir_path / "server.log", resolved_level))
    except Exception as exc:  # pragma: no cover
        logging.warning("Failed to attach file handler: %s", exc)

    # Quiet down third-party loggers that flood the console at INFO level.
    for noisy in (
        "httpx",
        "httpcore",
        "urllib3",
        "google_genai.models",
        "watchfiles.main",
        "asyncio",
    ):
        logging.getLogger(noisy).setLevel(logging.WARNING)

    # Keep uvicorn's access log visible but route it through our format.
    for uvl in ("uvicorn", "uvicorn.error", "uvicorn.access"):
        lg = logging.getLogger(uvl)
        lg.handlers = []
        lg.propagate = True

    _CONFIGURED = True
    logging.getLogger("core.logging_config").info(
        "Logging initialized: level=%s file=%s",
        logging.getLevelName(resolved_level),
        log_dir_path / "server.log",
    )


# -----------------------------------------------------------------------------
# ASGI middleware — stamps a request id and logs request start/end + duration
# -----------------------------------------------------------------------------

_logger = logging.getLogger("lemo.request")


async def request_id_middleware(request, call_next: Callable):  # type: ignore[no-untyped-def]
    """FastAPI HTTP middleware.

    Assigns a short correlation id, logs "--> METHOD path" at entry and
    "<-- status METHOD path (duration_ms)" at exit. Exceptions are re-raised
    after being logged with the same id.
    """
    req_id = f"r-{uuid.uuid4().hex[:6]}"
    token = set_request_id(req_id)
    start = time.perf_counter()
    method = request.method
    path = request.url.path
    query = request.url.query

    _logger.info("--> %s %s%s", method, path, f"?{query}" if query else "")

    try:
        response = await call_next(request)
    except Exception as exc:
        duration_ms = (time.perf_counter() - start) * 1000
        _logger.exception(
            "<-- ERR %s %s raised %s after %.1fms",
            method,
            path,
            type(exc).__name__,
            duration_ms,
        )
        _request_id_ctx.reset(token)
        raise
    else:
        duration_ms = (time.perf_counter() - start) * 1000
        status = getattr(response, "status_code", "?")
        _logger.info("<-- %s %s %s (%.1fms)", status, method, path, duration_ms)
        # Surface the request id back to the extension for client-side log correlation.
        try:
            response.headers["X-Request-Id"] = req_id
        except Exception:
            pass
        _request_id_ctx.reset(token)
        return response


__all__ = [
    "setup_logging",
    "request_id_middleware",
    "get_request_id",
    "set_request_id",
]
